"""Firmware feature profiles for Setup and Image Builder."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .flash import images_complete, repo_root


@dataclass(frozen=True)
class FeatureSet:
    wifi_web: bool = True
    ble: bool = True
    stock_applets: bool = True
    oled: bool = True
    sdcard: bool = True
    battery: bool = True
    uart_cmd: bool = True

    def as_dict(self) -> dict[str, bool]:
        return {
            "SUPPORT_WIFI_WEB": self.wifi_web,
            "SUPPORT_BLE": self.ble,
            "SUPPORT_STOCK_APPLETS": self.stock_applets and self.wifi_web,
            "SUPPORT_OLED": self.oled,
            "SUPPORT_SDCARD": self.sdcard,
            "SUPPORT_BATTERY": self.battery,
            "BUDDY_UART_CMD": self.uart_cmd,
        }

    @property
    def is_uart_slim(self) -> bool:
        return not self.wifi_web


PRESETS: dict[str, FeatureSet] = {
    "full": FeatureSet(),
    "headless": FeatureSet(oled=False, sdcard=False),
    "uart-slim": FeatureSet(
        wifi_web=False,
        ble=False,
        stock_applets=False,
        oled=False,
        sdcard=False,
        battery=True,
        uart_cmd=True,
    ),
    "no-ble": FeatureSet(ble=False),
}

PRESET_LABELS = {
    "full": "Full (portal + BLE + App Store + OLED + SD)",
    "headless": "Headless (no OLED / SD)",
    "uart-slim": "UART slim (serial + Neo USB only)",
    "no-ble": "No Bluetooth",
}

PUBLISHED_LABELS = {
    "full": "Full",
    "headless": "Headless (no screen / SD)",
    "uart-slim": "UART slim (no Wi-Fi / BLE)",
}


@dataclass(frozen=True)
class ImageProfile:
    id: str
    label: str
    path: Path
    uart_only: bool = False


def _profile_dirs_for_version(version: str) -> list[tuple[str, Path]]:
    root = repo_root() / "releases"
    return [
        ("full", root / version),
        ("headless", root / f"{version}-headless"),
        ("uart-slim", root / f"{version}-uart-slim"),
    ]


def discover_image_profiles(preferred_version: str = "1.0.0") -> list[ImageProfile]:
    """Find complete image folders for Setup’s profile picker."""
    found: list[ImageProfile] = []
    seen: set[Path] = set()

    for pid, path in _profile_dirs_for_version(preferred_version):
        if images_complete(path):
            resolved = path.resolve()
            if resolved in seen:
                continue
            seen.add(resolved)
            found.append(
                ImageProfile(
                    id=pid,
                    label=PUBLISHED_LABELS.get(pid, pid),
                    path=resolved,
                    uart_only=(pid == "uart-slim"),
                )
            )

    custom_root = repo_root() / "releases" / "custom"
    if custom_root.is_dir():
        for child in sorted(custom_root.iterdir(), key=lambda p: p.name.lower()):
            if not child.is_dir() or not images_complete(child):
                continue
            resolved = child.resolve()
            if resolved in seen:
                continue
            seen.add(resolved)
            meta = child / "profile.txt"
            uart = "uart" in child.name.lower()
            label = f"Custom · {child.name}"
            if meta.is_file():
                text = meta.read_text(encoding="utf-8", errors="replace")
                uart = uart or "SUPPORT_WIFI_WEB=n" in text or "# CONFIG_SUPPORT_WIFI_WEB is not set" in text
                for line in text.splitlines():
                    if line.startswith("label="):
                        label = line.split("=", 1)[1].strip() or label
            found.append(
                ImageProfile(id=f"custom:{child.name}", label=label, path=resolved, uart_only=uart)
            )

    bundled = Path(__file__).resolve().parent.parent / "images"
    if images_complete(bundled):
        resolved = bundled.resolve()
        if resolved not in seen:
            seen.add(resolved)
            found.insert(
                0,
                ImageProfile(id="bundled", label="Full (bundled)", path=resolved, uart_only=False),
            )

    return found


def write_sdkconfig_fragment(path: Path, features: FeatureSet, *, label: str = "") -> None:
    """Write a fragment suitable for SDKCONFIG_DEFAULTS chaining."""
    lines = [
        "# Generated by Neo2 Buddy Image Builder",
        f"# label={label}" if label else "# label=custom",
    ]
    for key, enabled in features.as_dict().items():
        if enabled:
            lines.append(f"CONFIG_{key}=y")
        else:
            lines.append(f"# CONFIG_{key} is not set")
    if not features.ble:
        lines.extend(
            [
                "# CONFIG_BT_ENABLED is not set",
                "# CONFIG_BT_CONTROLLER_ENABLED is not set",
                "# CONFIG_BT_NIMBLE_ENABLED is not set",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fragment_for_preset(preset_id: str) -> Path | None:
    mapping = {
        "headless": "profile_headless.defaults",
        "uart-slim": "profile_uart_slim.defaults",
        "no-ble": "profile_no_ble.defaults",
    }
    name = mapping.get(preset_id)
    if not name:
        return None
    path = repo_root() / "firmware" / "sdkconfig.d" / name
    return path if path.is_file() else None
