#!/usr/bin/env python3
"""Pack DndCompanion character.json into a compact binary blob + C header."""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

MAGIC = b"DND1"
MAX_SPELLS = 24
MAX_WEAPONS = 8
NAME_LEN = 16
CLASS_LEN = 12
SPELL_NAME = 20
WEAPON_NAME = 16
WEAPON_DMG = 12


def pad(s: str, n: int) -> bytes:
    b = (s or "").encode("ascii", errors="replace")[: n - 1]
    return b + b"\0" * (n - len(b))


def mod_bonus(score: int) -> int:
    return (int(score) - 10) // 2


def pack_character(data: dict) -> bytes:
    stats = data.get("stats") or {}
    spells = list(data.get("spells") or [])[:MAX_SPELLS]
    weapons = list(data.get("weapons") or [])[:MAX_WEAPONS]

    hdr = bytearray()
    hdr += MAGIC
    hdr += bytes([1])  # version
    hdr += pad(str(data.get("name", "Hero")), NAME_LEN)
    hdr += pad(str(data.get("class", "Adventurer")), CLASS_LEN)
    hdr += bytes([int(data.get("level", 1)) & 0xFF])
    hp = int(data.get("hp", 1)) & 0xFFFF
    hp_max = int(data.get("hp_max", hp)) & 0xFFFF
    hdr += struct.pack(">HH", hp, hp_max)
    hdr += bytes([int(data.get("ac", 10)) & 0xFF])
    for key in ("str", "dex", "con", "int", "wis", "cha"):
        hdr += bytes([int(stats.get(key, 10)) & 0xFF])
    hdr += bytes([len(spells), len(weapons), 0, 0])

    body = bytearray()
    for sp in spells:
        body += pad(str(sp.get("name", "Spell")), SPELL_NAME)
        body += bytes([int(sp.get("level", 0)) & 0xFF])
        body += bytes([1 if sp.get("prepared") else 0])
    for w in weapons:
        body += pad(str(w.get("name", "Weapon")), WEAPON_NAME)
        body += pad(str(w.get("dmg", "1d4")), WEAPON_DMG)

    return bytes(hdr) + bytes(body)


def write_header(blob: Path, out_h: Path, symbol: str = "dnd_config_blob") -> None:
    data = blob.read_bytes()
    lines = [
        "/* Auto-generated by pack_dnd_config.py — do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        f"#define DND_CONFIG_BLOB_LEN {len(data)}",
        f"static const uint8_t {symbol}[DND_CONFIG_BLOB_LEN] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    out_h.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("json", type=Path, help="character.json")
    ap.add_argument("-o", "--bin", type=Path, required=True, help="output .bin")
    ap.add_argument("--header", type=Path, help="optional C header with embedded blob")
    args = ap.parse_args()

    data = json.loads(args.json.read_text(encoding="utf-8"))
    blob = pack_character(data)
    if len(blob) > 1024:
        print(f"error: packed config {len(blob)} bytes exceeds 1024", file=sys.stderr)
        return 1
    args.bin.parent.mkdir(parents=True, exist_ok=True)
    args.bin.write_bytes(blob)
    print(f"OK: {args.bin} ({len(blob)} bytes)")
    if args.header:
        write_header(args.bin, args.header)
        print(f"OK: {args.header}")
    # helpful summary
    stats = data.get("stats") or {}
    print(
        f"  {data.get('name')} L{data.get('level')} {data.get('class')} "
        f"HP {data.get('hp')}/{data.get('hp_max')} AC {data.get('ac')} "
        f"INT {stats.get('int')} (mod {mod_bonus(stats.get('int', 10)):+d})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
